FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN npm install -g prisma

EXPOSE 3000

CMD ["npm", "run", "start:dev"]